debug: true
app:
  services:
    remote:
      url: ${REMOTE_SERVICE_URL:http://localhost}
      apiKey: ${REMOTE_SERVICE_API_KEY:123}
cache:
  timeoutInSeconds: ${DEFAULT_CACHE_TIMEOUT:5000000}
  redisPort: ${REDIS_PORT:6379}
  redisHost: ${REDIS_HOST:localhost}
  type: MEMORY
  configs:
    bookings:
      enabled: true
    clinics:
      enabled: true
    clinics_time_slots:
      enabled: true
      expirationInSeconds: 5000
    clinical_services:
      enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:booking
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 9000
  servlet:
    contextPath: /api
