apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-deployment
  labels:
    app: booking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: 316826375590.dkr.ecr.eu-west-1.amazonaws.com/therapie:latest
          ports:
            - containerPort: 9000